FROM apache/spark:3.5.3

USER root

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

CMD ["/opt/spark/bin/spark-submit", \
     "--master", "spark://spark-master:7077", \
     "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3", \
     "/app/traffic_streaming.py"]