FROM apache/airflow:2.9.0

USER root

# 1. Install Java AND the system libraries needed for Kerberos/C-extensions
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    gcc \
    python3-dev \
    libkrb5-dev && \
    apt-get autoremove -yqq --purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow

# 2. Now run your pip install
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt